// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"user/rpc/internal/logic"
	"user/rpc/internal/svc"
	"user/rpc/pb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) GetUser(ctx context.Context, in *__.GetUserReq) (*__.GetUserResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServiceServer) CreateUser(ctx context.Context, in *__.CreateUserReq) (*__.CreateUserResp, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UserServiceServer) Login(ctx context.Context, in *__.LoginReq) (*__.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServiceServer) Logout(ctx context.Context, in *__.LogoutReq) (*__.LogoutResp, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *UserServiceServer) UpdateUser(ctx context.Context, in *__.UpdateUserReq) (*__.UpdateUserResp, error) {
	l := logic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

func (s *UserServiceServer) DeleteUser(ctx context.Context, in *__.DeleteUserReq) (*__.DeleteUserResp, error) {
	l := logic.NewDeleteUserLogic(ctx, s.svcCtx)
	return l.DeleteUser(in)
}
